name = "bbqueue"
description = "DMA friendly lock-free BipBuffer"
version = "0.1.0"

licenses = ["MIT"]
authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau"]
tags = ["spark", "nostd", "embedded", "lockfree", "dma", "bipbuffer"]
website = "https://github.com/Fabien-Chouteau/bbqueue-ada"

long-description = """An Ada implementation of James Munns' BBQueue. See
https://github.com/jamesmunns/bbqueue"""
