name = "bbqueue"
description = ""
version = "0.1.0"

licenses = ["MIT"]
authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau"]
